### PR TITLE
feat(Github API): Use Github API instead of Puppeteer

### PR DESCRIPTION
**Pull request by ThallesP**
This PR will focus on change from Puppeteer to Github API
It is not ready yet!

Advantages of using Github API:
- Unauthorized users can do 10 requests per minute in a delay of 6 seconds, which is faster than the present delay of 6.5 seconds
- Authorized users can do 30 requests per minute in a delay of 2 seconds
- Low resource utilization

### CODE REVIEW

**Comment by ThallesP** [comment]
I couldn't find a reliable way of finding the repository's name through URL, if anyone knows some way, I'm accepting

**Comment by ThallesP** [comment]
@caioagiani Now it's up to you

**Comment by ThallesP** [comment]
Was using this PR and it is reaching some kind of "secondary rate limit"
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits
https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits

I will test it later and see if there's anyway to not get blocked.
We probably can detect when it happens and wait for a few seconds.

**Comment by caioagiani** [comment]
@ThallesP este PR foi muito bom, porém, o via API tem mais chances de limitar e para liberar é mais demorado.

**Comment by ThallesP** [comment]
Ele era mais rápido, mas tinha um problema onde o Github limitava
requisições repetidas, então o melhor é ficar com Puppeteer mesmo, eu só
lembrei agora que não tinha fechado esse PR kkkkk

**Pull request closed without merging**
